=== jaishah/mbwv4_POC/MBWv4_POC/WebContent/opensrs/ops.dtd
<!--
Opensrs Protocol Suite (OPS) v 0.1
(C) Copyright 2000, Tucows Inc.
All Rights Reserved
OPS Message Definition
-->
<!-- Envelope -->
<!ELEMENT OPS_envelope (header,body)>
<!-- header part -->
<!ELEMENT header (version)>
<!-- body part -->
<!ELEMENT body (data_block)>
<!-- data block -->
<!ELEMENT data_block (dt_assoc | dt_array |
dt_scalar| dt_scalarref)>
<!-- data types -->
<!ELEMENT dt_assoc (dt_assoc | dt_array| dt_scalar | dt_scalarref| (item)*)>
<!ELEMENT dt_array (dt_assoc | dt_array | dt_scalar | dt_scalarref | (item)*)>
<!ELEMENT dt_scalar (#PCDATA | dt_assoc | dt_array | dt_scalar | dt_scalarref)*>
<!ELEMENT dt_scalarref (#PCDATA | dt_assoc | dt_array | dt_scalar | dt_scalarref)*>
<!ELEMENT item (#PCDATA | dt_assoc | dt_array | dt_scalar | dt_scalarref)*>
<!ATTLIST item
	key CDATA #REQUIRED
	class CDATA #IMPLIED >
<!ELEMENT version (#PCDATA)>
<!-- document information entities -->
<!ENTITY company 'Tucows'>
<!ENTITY copyright '2000, Tucows'>

=== jaishah/mbwv4_POC/MBWv4_POC/WebContent/opensrs/get_dns_zone.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<!DOCTYPE OPS_envelope SYSTEM 'ops.dtd'>
<OPS_envelope>
	<header>
		<version>0.9</version>
	</header>
	<body>
		<data_block>
			<dt_assoc>
				<item key="protocol">XCP</item>
				<item key="action">get_dns_zone</item>
				<item key="object">domain</item>
				<item key="attributes">
					<dt_assoc>
						<item key="domain">{$term$}</item>
					</dt_assoc>
				</item>
			</dt_assoc>
		</data_block>
	</body>
</OPS_envelope>

=== jaishah/mbwv4_POC/MBWv4_POC/WebContent/opensrs/process_pending-response.xml
<?xml version='1.0' encoding="UTF-8" standalone="no" ?>
<!DOCTYPE OPS_envelope SYSTEM "ops.dtd">
<OPS_envelope>
 <header>
  <version>0.9</version>
  </header>
 <body>
  <data_block>
   <dt_assoc>
    <item key="protocol">XCP</item>
    <item key="object">DOMAIN</item>
    <item key="response_code">200</item>
    <item key="is_success">1</item>
    <item key="response_text">Domain registration successfully completed
Only Individuals can choose not to have their personal info displayed.</item>
    <item key="action">REPLY</item>
    <item key="attributes">
     <dt_assoc>
      <item key="whois_privacy_state">disabled</item>
      <item key="order_id">2559571</item>
      <item key="id">910428</item>
      <item key="f_auto_renew">N</item>
      <item key="registration expiration date">2013-08-03 10:27:24</item>
     </dt_assoc>
    </item>
   </dt_assoc>
  </data_block>
 </body>
</OPS_envelope>

=== jaishah/mbwv4_POC/MBWv4_POC/WebContent/opensrs/create_dns_zone.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<!DOCTYPE OPS_envelope SYSTEM 'ops.dtd'>
	<OPS_envelope>
		<header>
			<version>0.9</version>
		</header>
		<body>
			<data_block>
				<dt_assoc>
					<item key="protocol">XCP</item>
					<item key="action">CREATE_DNS_ZONE</item>
					<item key="object">DOMAIN</item>
					<item key="attributes">
					<dt_assoc>
						<item key="domain">{$term$}</item>
						<item key="records">
							<dt_assoc>
								<item key="A">
									<dt_array>
										<item key="0">
											<dt_assoc>
												<item key="subdomain"></item>
												<item key="ip_address">123.123.123.2</item>
											</dt_assoc>
										</item>
										<item key="1">
											<dt_assoc>
												<item key="subdomain">*</item>
												<item key="ip_address">123.123.123.3</item>
											</dt_assoc>
										</item>
										<item key="2">
											<dt_assoc>
												<item key="subdomain">www</item>
												<item key="ip_address">123.123.123.4</item>
											</dt_assoc>
										</item>
									</dt_array>
								</item>
								<item key="CNAME">
									<dt_array>
										<item key="0">
											<dt_assoc>
												<item key="subdomain">portal</item>
												<item key="hostname">www.{$term$}</item>
											</dt_assoc>
										</item>
									</dt_array>
								</item>
								<item key="MX">
									<dt_array>
										<item key="0">
											<dt_assoc>
												<item key="subdomain"></item>
												<item key="hostname">mx.{$term$}.cust.test.hostedemail.com</item>
												<item key="priority">10</item>
											</dt_assoc>
										</item>
									</dt_array>
								</item>
								<item key="TXT">
									<dt_array>
										<item key="0">
											<dt_assoc>
												<item key="subdomain">mail</item>
												<item key="text">v=spf1exists:{$term$} -all</item>
											</dt_assoc>
										</item>
									</dt_array>
								</item>
								<item key="AAAA">
									<dt_array>
										<item key="0">
											<dt_assoc>
												<item key="subdomain">itportal</item>
												<item key="ipv6_address">2001:00ab:0000:00a1:0001:000b:00cc:00de</item>
											</dt_assoc>
										</item>
									</dt_array>
								</item>
								<item key="SRV">
									<dt_array>
										<item key="0">
											<dt_assoc>
												<item key="subdomain">itcontrol</item>
												<item key="hostname">control.{$term$}</item>
												<item key="port">443</item>	
												<item key="priority">10</item>
												<item key="weight">1</item>
											</dt_assoc>
										</item>
									</dt_array>
								</item>
							</dt_assoc>
						</item>
					</dt_assoc>
				</item>
			</dt_assoc>
		</data_block>
	</body>
</OPS_envelope>
