=== jaishah/mbwv4_POC/MBWv4_POC/WebContent/opensrs/ops.dtd
<!--
Opensrs Protocol Suite (OPS) v 0.1
(C) Copyright 2000, Tucows Inc.
All Rights Reserved
OPS Message Definition
-->
<!-- Envelope -->
<!ELEMENT OPS_envelope (header,body)>
<!-- header part -->
<!ELEMENT header (version)>
<!-- body part -->
<!ELEMENT body (data_block)>
<!-- data block -->
<!ELEMENT data_block (dt_assoc | dt_array |
dt_scalar| dt_scalarref)>
<!-- data types -->
<!ELEMENT dt_assoc (dt_assoc | dt_array| dt_scalar | dt_scalarref| (item)*)>
<!ELEMENT dt_array (dt_assoc | dt_array | dt_scalar | dt_scalarref | (item)*)>
<!ELEMENT dt_scalar (#PCDATA | dt_assoc | dt_array | dt_scalar | dt_scalarref)*>
<!ELEMENT dt_scalarref (#PCDATA | dt_assoc | dt_array | dt_scalar | dt_scalarref)*>
<!ELEMENT item (#PCDATA | dt_assoc | dt_array | dt_scalar | dt_scalarref)*>
<!ATTLIST item
	key CDATA #REQUIRED
	class CDATA #IMPLIED >
<!ELEMENT version (#PCDATA)>
<!-- document information entities -->
<!ENTITY company 'Tucows'>
<!ENTITY copyright '2000, Tucows'>

=== jaishah/mbwv4_POC/MBWv4_POC/WebContent/opensrs/view_status.xml
<?xml version="1.0" encoding="UTF-8" standalone='yes'?>
<!DOCTYPE OPS_envelope SYSTEM 'ops.dtd'>
<OPS_envelope>
<header>
<version>0.9</version>
</header>
<body>
<data_block>
<dt_assoc>
<item key="protocol">XCP</item>
<item key="action">get</item>
<item key="object">domain</item>
<item key="attributes">
<dt_assoc>
<item key="domain">{$term$}</item>
<item key="type">status</item>
</dt_assoc>
</item>
</dt_assoc>
</data_block>
</body>
</OPS_envelope>

=== jaishah/mbwv4_POC/MBWv4_POC/WebContent/opensrs/modify_status.xml
<?xml version="1.0" encoding="UTF-8" standalone='yes'?>
<!DOCTYPE OPS_envelope SYSTEM 'ops.dtd'>
<OPS_envelope>
<header>
<version>0.9</version>
</header>
<body>
<data_block>
<dt_assoc>
<item key="protocol">XCP</item>
<item key="action">modify</item>
<item key="object">domain</item>
<item key="attributes">
<dt_assoc>
<item key="affect_domains">0</item>
<item key="lock_state">{$lock$}</item>
<item key="data">status</item>
<item key="domain">{$term$}</item>
</dt_assoc>
</item>
</dt_assoc>
</data_block>
</body>
</OPS_envelope>

=== jaishah/mbwv4_POC/MBWv4_POC/WebContent/opensrs/sw_register-request.xml
<?xml version='1.0' encoding='UTF-8' standalone='no' ?>
<!DOCTYPE OPS_envelope SYSTEM 'ops.dtd'>
<OPS_envelope>
	<header>
		<version>0.9</version>
	</header>
	<body>
		<data_block>
			<dt_assoc>
				<item key="protocol">XCP</item>
				<item key="action">SW_REGISTER</item>
				<item key="object">DOMAIN</item>
				<item key="registrant_ip">10.20.10.7</item>
				<item key="attributes">
					<dt_assoc>
						<item key="auto_renew"/>
						<item key="link_domains">0</item>
						<item key="reg_domain"/>
						<item key="f_lock_domain">1</item>
						<item key="f_whois_privacy">1</item>
						<item key="f_parkp">Y</item>
						<item key="domain">shah.co.uk</item>
						<item key="affiliate_id"/>
						<item key="period">1</item>
						<item key="reg_type">new</item>
						<item key="comments">Blahdeblahdeblah</item>
						<item key="reg_username">bcsg</item>
						<item key="custom_tech_contact">0</item>
						<item key="contact_set">
							<dt_assoc>
								<item key="owner">
									<dt_assoc>
										<item key="first_name">Phil</item>
										<item key="last_name">Bircumshaw</item>
										<item key="org_name">BCSG</item>
										<item key="address1">130 Old Street</item>
										<item key="city">London</item>
										<item key="state">London</item>
										<item key="country">GB</item>
										<item key="postal_code">EC1V 9BD</item>
										<item key="phone">+1.41655511221234</item>
										<item key="email">phil.bircumshaw@bcsg.com</item>
									</dt_assoc>								
								</item>
								<item key="billing">
									<dt_assoc>
										<item key="first_name">Phil</item>
										<item key="last_name">Bircumshaw</item>
										<item key="phone">+1.41655511221234</item>
										<item key="fax">+1.41655511221235</item>
										<item key="email">phil.bircumshaw@bcsg.com</item>
										<item key="org_name">BCSG Inc</item>
										<item key="address1">130 Old Street</item>
										<item key="address2"></item>
										<item key="address3"></item>
										<item key="city">London</item>
										<item key="state">London</item>
										<item key="country">GB</item>
										<item key="postal_code">EC1V 9BD</item>
									</dt_assoc>
								</item>						
							</dt_assoc>
						</item>	
						<item key="nameserver_list">
							<dt_array>
								<item key="0">
									<dt_assoc>
										<item key="sortorder">1</item>
										<item key="name">ns1.systemdns.com</item>
									</dt_assoc>
								</item>
								<item key="1">
									<dt_assoc>
										<item key="sortorder">2</item>
										<item key="name">ns2.systemdns.com</item>
									</dt_assoc>
								</item>
							</dt_array>
						</item>
						<item key="reg_password">Welcome1</item>
						<item key="encoding_type"/>
						<item key="custom_nameservers">1</item>
					</dt_assoc>
				</item>
			</dt_assoc>
		</data_block>
	</body>
</OPS_envelope>

=== jaishah/mbwv4_POC/MBWv4_POC/WebContent/opensrs/sw_register.xml
<?xml version='1.0' encoding='UTF-8' standalone='no' ?>
<!DOCTYPE OPS_envelope SYSTEM 'ops.dtd'>
<OPS_envelope>
	<header>
		<version>0.9</version>
	</header>
	<body>
		<data_block>
			<dt_assoc>
				<item key="protocol">XCP</item>
				<item key="action">SW_REGISTER</item>
				<item key="object">DOMAIN</item>
				<item key="registrant_ip">10.20.10.7</item>
				<item key="attributes">
					<dt_assoc>
						<item key="auto_renew"/>
						<item key="link_domains">0</item>
						<item key="reg_domain"/>
						<item key="f_lock_domain">1</item>
						<item key="f_whois_privacy">1</item>
						<item key="f_parkp">Y</item>
						<item key="domain">{$term$}</item>
						<item key="affiliate_id"/>
						<item key="period">1</item>
						<item key="reg_type">new</item>
						<item key="comments"></item>
						<item key="reg_username">{$user$}</item>
						<item key="custom_tech_contact">0</item>
						<item key="contact_set">
							<dt_assoc>
								<item key="owner">
									<dt_assoc>
										<item key="first_name">Piers</item>
										<item key="last_name">Chead</item>
										<item key="org_name">Business Centric Service Group Ltd</item>
										<item key="address1">1000 N. West Street, Suite 1200</item>
										<item key="address2">New Castle County</item>
										<item key="city">Wilmington</item>
										<item key="state">Delaware</item>
										<item key="country">US</item>
										<item key="postal_code">19801</item>
										<item key="phone">+1.4165551122x1</item>
										<item key="email">finance@bcsg.com</item>
									</dt_assoc>								
								</item>
								<item key="billing">
									<dt_assoc>
										<item key="first_name">Piers</item>
										<item key="last_name">Chead</item>
										<item key="phone">+1.4165551122x1</item>
										<item key="fax"></item>
										<item key="email">finance@bcsg.com</item>
										<item key="org_name">Business Centric Service Group Inc.</item>
										<item key="address1">1000 N. West Street, Suite 1200</item>
										<item key="address2">New Castle County</item>
										<item key="address3"></item>
										<item key="city">Wilmington</item>
										<item key="state">Delaware</item>
										<item key="country">US</item>
										<item key="postal_code">19801</item>
									</dt_assoc>
								</item>						
							</dt_assoc>
						</item>	
						<item key="nameserver_list">
							<dt_array>
								<item key="0">
									<dt_assoc>
										<item key="sortorder">1</item>
										<item key="name">ns1.systemdns.com</item>
									</dt_assoc>
								</item>
								<item key="1">
									<dt_assoc>
										<item key="sortorder">2</item>
										<item key="name">ns2.systemdns.com</item>
									</dt_assoc>
								</item>
							</dt_array>
						</item>
						<!--{$nexus_information$}-->
						<item key="reg_password">{$pwd$}</item>
						<item key="encoding_type"/>
						<item key="custom_nameservers">1</item>
					</dt_assoc>
				</item>
			</dt_assoc>
		</data_block>
	</body>
</OPS_envelope>

=== jaishah/mbwv4_POC/MBWv4_POC/WebContent/opensrs/name_suggest.xml
<?xml version='1.0' encoding='UTF-8' standalone='no' ?>
<!DOCTYPE OPS_envelope SYSTEM 'ops.dtd'>
<OPS_envelope>   
	<header>       
		<version>0.9</version>   
	</header>
	<body>
		<data_block>
			<dt_assoc>
				<item key='attributes'>
					<dt_assoc>
						<item key='services'>
							<dt_array>
								<item key='0'>lookup</item>
								<item key='1'>suggestion</item>
							</dt_array>
						</item>
						<item key='searchstring'>{$term$}</item>
						<item key='languages'>
							<dt_array>
								<item key='0'>en</item>
							</dt_array>
						</item>
						<item key='tlds'>
							<dt_array>
								<item key='0'>.co.uk</item>
								<item key='1'>.com</item>
								<item key='2'>.net</item>
								<item key='3'>.org</item>
								<item key='4'>.biz</item>
							</dt_array>
						</item>
						<item key='pre-reg'>0</item>
					</dt_assoc>
				</item>
				<item key='object'>DOMAIN</item>
				<item key='action'>NAME_SUGGEST</item>
				<item key='protocol'>XCP</item>
			</dt_assoc>
		</data_block>
	</body>
</OPS_envelope>

=== jaishah/mbwv4_POC/MBWv4_POC/WebContent/opensrs/process_pending-request.xml
<?xml version='1.0' encoding='UTF-8' standalone='no' ?>
<!DOCTYPE OPS_envelope SYSTEM 'ops.dtd'>
	<OPS_envelope>
		<header>
			<version>0.9</version>
			<msg_id>2.21765911726198</msg_id>
			<msg_type>standard</msg_type>
		</header>
		<body>
			<data_block>
				<dt_assoc>
					<item key="protocol">XCP</item>
					<item key="action">process_pending</item>
					<item key="object">domain</item>
					<item key="attributes">
						<dt_assoc>
							<item key="owner_address">myemail@example.com</item>
							<item key="order_id">2559571</item>
						</dt_assoc>
					</item>
				</dt_assoc>
			</data_block>
		</body>
</OPS_envelope>

=== jaishah/mbwv4_POC/MBWv4_POC/WebContent/opensrs/modify_domain.xml
<?xml version="1.0" encoding="UTF-8" standalone='yes'?>
<!DOCTYPE OPS_envelope SYSTEM 'ops.dtd'>
<OPS_envelope>
<header>
<version>0.9</version>
</header>
<body>
<data_block>
<dt_assoc>
<item key="protocol">XCP</item>
<item key="action">modify</item>
<item key="object">domain</item>
<item key="attributes">
<dt_assoc>
<item key="domain">{$term$}</item>
<item key="report_email"/>
<item key="state">{$state$}</item>
<item key="data">whois_privacy_state</item>
</dt_assoc>
</item>
</dt_assoc>
</data_block>
</body>
</OPS_envelope>

=== jaishah/mbwv4_POC/MBWv4_POC/WebContent/opensrs/revoke.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>

<!DOCTYPE OPS_envelope SYSTEM 'ops.dtd'>

<OPS_envelope>

   <header>

      <version>0.9</version>

   </header>

   <body>

      <data_block>

         <dt_assoc>

            <item key="protocol">XCP</item>

            <item key="action">REVOKE</item>

            <item key="object">DOMAIN</item>

            <item key="attributes">

               <dt_assoc>

                  <item key="reseller">BCSG</item>

                  <item key="domain">{$term$}</item>

                  <item key="notes">BCSG</item>

               </dt_assoc>

            </item>

         </dt_assoc>

      </data_block>

   </body>

</OPS_envelope>
